begin;
select plan(50);
select has_type('public','price_mode'); select has_type('public','order_type'); select has_type('public','order_status'); select has_type('public','fulfilment_type');
select has_table('public','admin_profiles'); select has_table('public','site_settings'); select has_table('public','categories'); select has_table('public','products');
select has_table('public','product_images'); select has_table('public','product_variants'); select has_table('public','flavours'); select has_table('public','product_flavours');
select has_table('public','allergens'); select has_table('public','product_allergens'); select has_table('public','availability_blocks'); select has_table('public','orders');
select has_table('public','order_items'); select has_table('public','custom_order_details'); select has_table('public','order_reference_images'); select has_table('public','order_status_history'); select has_table('public','email_events');
select col_is_pk('public','admin_profiles','user_id'); select col_is_pk('public','orders','id'); select col_is_pk('public','custom_order_details','order_id');
select has_fk('public','products'); select has_fk('public','order_items'); select has_fk('public','order_status_history');
select has_index('public','categories','categories_slug_key'); select has_index('public','products','products_slug_key'); select has_index('public','products','products_category_id_idx');
select has_index('public','product_images','product_images_one_primary_idx'); select has_index('public','orders','orders_human_reference_key'); select has_index('public','orders','orders_status_idx');
select has_index('public','orders','orders_requested_date_idx'); select has_index('public','orders','orders_created_at_idx'); select has_index('public','order_items','order_items_order_id_idx');
select has_index('public','order_status_history','order_status_history_order_id_idx'); select has_index('public','availability_blocks','availability_blocks_dates_idx');
select is((select relrowsecurity from pg_class where oid='public.admin_profiles'::regclass),true,'admin_profiles has RLS');
select is((select relrowsecurity from pg_class where oid='public.site_settings'::regclass),true,'site_settings has RLS');
select is((select relrowsecurity from pg_class where oid='public.categories'::regclass),true,'categories has RLS');
select is((select relrowsecurity from pg_class where oid='public.products'::regclass),true,'products has RLS');
select is((select relrowsecurity from pg_class where oid='public.availability_blocks'::regclass),true,'availability has RLS');
select is((select relrowsecurity from pg_class where oid='public.orders'::regclass),true,'orders has RLS');
select is((select relrowsecurity from pg_class where oid='public.order_items'::regclass),true,'order_items has RLS');
select is((select relrowsecurity from pg_class where oid='public.custom_order_details'::regclass),true,'custom details has RLS');
select is((select relrowsecurity from pg_class where oid='public.order_reference_images'::regclass),true,'reference metadata has RLS');
select is((select relrowsecurity from pg_class where oid='public.order_status_history'::regclass),true,'history has RLS');
select is((select relrowsecurity from pg_class where oid='public.email_events'::regclass),true,'email events has RLS');
select is((select count(*)::integer from public.allergens),14,'seed includes 14 allergens');
select * from finish(); rollback;
