begin;
select plan(50);
select has_type('public'::name,'price_mode'::name); select has_type('public'::name,'order_type'::name); select has_type('public'::name,'order_status'::name); select has_type('public'::name,'fulfilment_type'::name);
select has_table('public'::name,'admin_profiles'::name); select has_table('public'::name,'site_settings'::name); select has_table('public'::name,'categories'::name); select has_table('public'::name,'products'::name);
select has_table('public'::name,'product_images'::name); select has_table('public'::name,'product_variants'::name); select has_table('public'::name,'flavours'::name); select has_table('public'::name,'product_flavours'::name);
select has_table('public'::name,'allergens'::name); select has_table('public'::name,'product_allergens'::name); select has_table('public'::name,'availability_blocks'::name); select has_table('public'::name,'orders'::name);
select has_table('public'::name,'order_items'::name); select has_table('public'::name,'custom_order_details'::name); select has_table('public'::name,'order_reference_images'::name); select has_table('public'::name,'order_status_history'::name); select has_table('public'::name,'email_events'::name);
select col_is_pk('public'::name,'admin_profiles'::name,'user_id'::name); select col_is_pk('public'::name,'orders'::name,'id'::name); select col_is_pk('public'::name,'custom_order_details'::name,'order_id'::name);
select has_fk('public'::name,'products'::name,'products has a foreign key'); select has_fk('public'::name,'order_items'::name,'order_items has a foreign key'); select has_fk('public'::name,'order_status_history'::name,'order_status_history has a foreign key');
select has_index('public'::name,'categories'::name,'categories_slug_key'::name); select has_index('public'::name,'products'::name,'products_slug_key'::name); select has_index('public'::name,'products'::name,'products_category_id_idx'::name);
select has_index('public'::name,'product_images'::name,'product_images_one_primary_idx'::name); select has_index('public'::name,'orders'::name,'orders_human_reference_key'::name); select has_index('public'::name,'orders'::name,'orders_status_idx'::name);
select has_index('public'::name,'orders'::name,'orders_requested_date_idx'::name); select has_index('public'::name,'orders'::name,'orders_created_at_idx'::name); select has_index('public'::name,'order_items'::name,'order_items_order_id_idx'::name);
select has_index('public'::name,'order_status_history'::name,'order_status_history_order_id_idx'::name); select has_index('public'::name,'availability_blocks'::name,'availability_blocks_dates_idx'::name);
select is((select relrowsecurity from pg_class where oid='public.admin_profiles'::regclass),true,'admin_profiles has RLS');
select is((select relrowsecurity from pg_class where oid='public.site_settings'::regclass),true,'site_settings has RLS');
select is((select relrowsecurity from pg_class where oid='public.categories'::regclass),true,'categories has RLS');
select is((select relrowsecurity from pg_class where oid='public.products'::regclass),true,'products has RLS');
select is((select relrowsecurity from pg_class where oid='public.availability_blocks'::regclass),true,'availability has RLS');
select is((select relrowsecurity from pg_class where oid='public.orders'::regclass),true,'orders has RLS');
select is((select relrowsecurity from pg_class where oid='public.order_items'::regclass),true,'order_items has RLS');
select is((select relrowsecurity from pg_class where oid='public.custom_order_details'::regclass),true,'custom details has RLS');
select is((select relrowsecurity from pg_class where oid='public.order_reference_images'::regclass),true,'reference metadata has RLS');
select is((select relrowsecurity from pg_class where oid='public.order_status_history'::regclass),true,'history has RLS');
select is((select relrowsecurity from pg_class where oid='public.email_events'::regclass),true,'email events has RLS');
select is((select count(*)::integer from public.allergens),14,'seed includes 14 allergens');
select * from finish(); rollback;
