import { Link } from 'react-router-dom'
import { CatalogImage } from '../components/CatalogImage'
import { ErrorState, LoadingState } from '../components/ui/AsyncState'
import { ProductCard } from '../features/catalog/ProductCard'
import { useCategories, useFeaturedProducts } from '../features/catalog/hooks'
import { BusinessDetails } from '../features/site/BusinessDetails'
import { useSiteSettings } from '../features/site/hooks'

export function HomePage() {
  const settings = useSiteSettings(), featured = useFeaturedProducts(), categories = useCategories()
  if (settings.isLoading) return <div className="page-shell"><LoadingState label="Preparando la web…" /></div>
  if (settings.isError || !settings.data) return <div className="page-shell py-16"><ErrorState message="No se pudo conectar con la configuración pública. Comprueba la configuración local de Supabase." /></div>
  const site = settings.data
  return <>
    <section className="overflow-hidden bg-rose-50"><div className="page-shell grid items-center gap-10 py-14 md:grid-cols-2 md:py-24"><div><p className="eyebrow">{site.business_name}</p><h1 className="font-serif text-5xl font-semibold leading-[1.05] tracking-tight text-rose-950 sm:text-6xl">{site.hero_title}</h1>{site.hero_subtitle && <p className="mt-6 max-w-xl text-lg leading-8 text-stone-700">{site.hero_subtitle}</p>}<div className="mt-8 flex flex-wrap gap-3"><Link className="button-primary" to="/catalogo">Ver catálogo</Link><Link className="button-secondary" to="/personalizado">Productos personalizados</Link></div></div><div className="aspect-[4/3] overflow-hidden rounded-[2.5rem] shadow-xl shadow-rose-900/10"><CatalogImage path={site.hero_image} alt={site.hero_title} eager className="h-full w-full object-cover" /></div></div></section>
    <section className="page-shell -mt-5 relative z-10"><div className={`rounded-2xl px-6 py-5 shadow-sm ${site.accepting_orders ? 'bg-emerald-900 text-white' : 'bg-amber-100 text-amber-950'}`}><p className="font-semibold">{site.accepting_orders ? 'Actualmente aceptamos nuevas solicitudes' : 'Solicitudes temporalmente cerradas'}</p>{!site.accepting_orders && <p className="mt-1 text-sm leading-6">{site.closed_orders_message}</p>}<p className="mt-1 text-sm opacity-80">El catálogo permanece disponible para consultar.</p></div></section>
    <section className="page-shell section-space"><div className="section-heading"><div><p className="eyebrow">Una selección especial</p><h2>Productos destacados</h2></div><Link to="/catalogo">Ver todo el catálogo →</Link></div>{featured.isLoading ? <LoadingState /> : featured.isError ? <ErrorState /> : featured.data?.length ? <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{featured.data.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <p className="mt-8 text-stone-600">Pronto encontrarás aquí nuestra selección destacada.</p>}</section>
    <section className="bg-stone-100"><div className="page-shell section-space"><div className="section-heading"><div><p className="eyebrow">Encuentra tu favorito</p><h2>Categorías</h2></div></div>{categories.isLoading ? <LoadingState /> : categories.isError ? <ErrorState /> : <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.data?.map((category) => <Link key={category.id} to={`/catalogo?categoria=${category.slug}`} className="group relative min-h-56 overflow-hidden rounded-3xl bg-white"><CatalogImage path={category.image_path} alt={category.name} className="absolute inset-0 h-full w-full object-cover opacity-55 transition group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-stone-950/80 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-white"><h3 className="font-serif text-2xl font-semibold">{category.name}</h3>{category.description && <p className="mt-1 text-sm text-stone-200">{category.description}</p>}</div></Link>)}</div>}</div></section>
    <section className="page-shell section-space"><div className="text-center"><p className="eyebrow">Cómo funciona</p><h2 className="font-serif text-4xl font-semibold">Una solicitud sencilla y personal</h2></div><ol className="mt-10 grid gap-5 md:grid-cols-3">{[['01','Elige','Consulta el catálogo o piensa en una creación personalizada.'],['02','Envía tu solicitud','Indica lo que necesitas cuando el formulario esté disponible.'],['03','Confirmamos contigo','El negocio contactará para confirmar fecha, detalles y precio.']].map(([n,title,text]) => <li className="rounded-3xl border border-stone-200 bg-white p-7" key={n}><span className="font-serif text-3xl text-rose-300">{n}</span><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 leading-6 text-stone-600">{text}</p></li>)}</ol><p className="mt-6 text-center text-sm font-medium text-stone-600">Enviar una solicitud no supone una compra ni una reserva confirmada.</p></section>
    <section className="page-shell"><div className="rounded-[2.5rem] bg-rose-950 px-7 py-12 text-rose-50 sm:px-12"><p className="eyebrow text-rose-300">Hecho para ti</p><h2 className="font-serif text-4xl font-semibold">{site.custom_orders_title}</h2>{site.custom_orders_description && <p className="mt-4 max-w-2xl text-lg leading-8 text-rose-100/80">{site.custom_orders_description}</p>}<Link className="mt-7 inline-block rounded-full bg-white px-6 py-3 font-semibold text-rose-950" to="/personalizado">Saber más</Link></div></section>
    <section className="page-shell section-space"><div className="section-heading"><div><p className="eyebrow">Estamos cerca</p><h2>Información del negocio</h2></div><Link to="/contacto">Contacto →</Link></div><div className="mt-8"><BusinessDetails settings={site} /></div></section>
  </>
}
